package com.helm.dispatch

import com.helm.data.DispatchCadence
import com.helm.data.DispatchReport
import com.helm.data.HelmRepository
import com.helm.data.LogEntry
import com.helm.data.LogGroup
import com.helm.data.LogKind
import com.helm.util.Format
import kotlinx.coroutines.flow.first

/**
 * Builds "The Dispatch" — a personal newsletter summarizing the last period's
 * screen time, money, health and habits into a markdown report.
 */
class DispatchGenerator(private val repo: HelmRepository) {

    suspend fun generate(cadence: DispatchCadence): DispatchReport {
        val days = if (cadence == DispatchCadence.WEEKLY) 7 else 1
        val now = System.currentTimeMillis()
        val fromDay = Format.dayKeyDaysAgo(days - 1, now)
        val toDay = Format.dayKey(now)
        val fromMillis = Format.startOfDaysAgo(days - 1, now)

        val currency = repo.settings.first().currency
        val usage = repo.usageBetween(fromDay, toDay).first()
        val logs = repo.logsBetween(fromMillis, now)

        val totalScreen = usage.sumOf { it.totalMillis }
        val avgPerDay = if (days > 0) totalScreen / days else totalScreen
        val topApps = usage.take(5)

        val expenses = logs.filter { it.kind == LogKind.EXPENSE }.sumOf { it.value ?: 0.0 }
        val income = logs.filter { it.kind == LogKind.INCOME }.sumOf { it.value ?: 0.0 }
        val moods = logs.filter { it.kind == LogKind.MOOD }.mapNotNull { it.value }
        val avgMood = if (moods.isNotEmpty()) moods.average() else null
        val sleep = logs.filter { it.kind == LogKind.SLEEP }.mapNotNull { it.value }
        val avgSleep = if (sleep.isNotEmpty()) sleep.average() else null
        val steps = logs.filter { it.kind == LogKind.STEPS }.sumOf { it.value ?: 0.0 }
        val workouts = logs.count { it.kind == LogKind.WORKOUT }
        val habits = logs.filter { it.kind == LogKind.HABIT }
        val weights = logs.filter { it.kind == LogKind.WEIGHT }.sortedBy { it.timestamp }

        val period = "${Format.pretty(fromMillis)} – ${Format.pretty(now)}"
        val sb = StringBuilder()
        sb.appendLine("# The Dispatch")
        sb.appendLine("### $period · ${cadence.display.lowercase()} edition")
        sb.appendLine()

        // Headline
        val headline = "${Format.duration(avgPerDay)}/day on screen · " +
            (avgMood?.let { "mood ${"%.1f".format(it)}/5 · " } ?: "") +
            "net ${currency}${"%.0f".format(income - expenses)}"

        // Screen time
        sb.appendLine("## 📱 Screen time")
        sb.appendLine("- Total: **${Format.duration(totalScreen)}** (${Format.duration(avgPerDay)}/day)")
        if (topApps.isNotEmpty()) {
            sb.appendLine("- Top apps:")
            topApps.forEach { sb.appendLine("  - ${it.appLabel} — ${Format.duration(it.totalMillis)} (${it.launchCount} opens)") }
        } else {
            sb.appendLine("- _No usage recorded yet. Grant Usage access to start tracking._")
        }
        sb.appendLine()

        // Money
        sb.appendLine("## 💰 Money")
        sb.appendLine("- Spent: **${currency}${"%.0f".format(expenses)}** · Earned: **${currency}${"%.0f".format(income)}** · Net: **${currency}${"%.0f".format(income - expenses)}**")
        topCategories(logs.filter { it.kind == LogKind.EXPENSE }).take(3).forEach { (cat, amt) ->
            sb.appendLine("  - $cat — ${currency}${"%.0f".format(amt)}")
        }
        sb.appendLine()

        // Health
        sb.appendLine("## ❤️ Health")
        avgSleep?.let { sb.appendLine("- Avg sleep: **${"%.1f".format(it)}h**") }
        if (steps > 0) sb.appendLine("- Steps: **${"%,.0f".format(steps)}**")
        if (workouts > 0) sb.appendLine("- Workouts: **$workouts**")
        if (weights.size >= 2) {
            val delta = (weights.last().value ?: 0.0) - (weights.first().value ?: 0.0)
            sb.appendLine("- Weight change: **${if (delta >= 0) "+" else ""}${"%.1f".format(delta)} kg**")
        }
        if (avgSleep == null && steps == 0.0 && workouts == 0 && weights.size < 2) {
            sb.appendLine("- _Log sleep, steps, workouts or weight to see health trends here._")
        }
        sb.appendLine()

        // Habits & mood
        sb.appendLine("## ✅ Habits & mood")
        if (habits.isNotEmpty()) {
            habits.groupingBy { it.title }.eachCount().entries
                .sortedByDescending { it.value }
                .take(5)
                .forEach { sb.appendLine("- ${it.key}: ${it.value}×") }
        } else {
            sb.appendLine("- _No habits logged this period._")
        }
        avgMood?.let { sb.appendLine("- Average mood: **${"%.1f".format(it)}/5** over ${moods.size} check-ins") }
        sb.appendLine()

        sb.appendLine("---")
        sb.appendLine("_Generated by Helm. Keep your hand on the wheel._")

        return DispatchReport(
            createdAt = now,
            periodLabel = period,
            headline = headline,
            markdown = sb.toString(),
        )
    }

    private fun topCategories(entries: List<LogEntry>): List<Pair<String, Double>> =
        entries.groupBy { it.category ?: "Uncategorized" }
            .map { (cat, list) -> cat to list.sumOf { it.value ?: 0.0 } }
            .sortedByDescending { it.second }
}
